# Generated by Django 2.0.7 on 2018-07-14 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'permissions': (('can_create', 'Can create'),)},
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('vacc', 'Vaccine'), ('demog', 'Demographic'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
