# Generated by Django 2.0.7 on 2018-07-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180714_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
    ]
